const API = '/api';
const state = {
  activeTab: 'dashboard', currentPath: 'root', fileSearch: '', serviceFilter: 'all', serviceSearch: '', uptimeSeconds: 0, auth: { authenticated: false, user: null, registration_open: false },
  stats: { cpu:0, ram:0, temp:0, networkUp:0, networkDown:0, serverName:'NEXUS NAS', platform:'NAS', nasRoot:'root', disks:[] },
  files: { root:[{id:'f1',name:'Media',type:'folder',updatedAt:'2026-06-25',path:'Media'},{id:'f2',name:'Backups',type:'folder',updatedAt:'2026-06-20',path:'Backups'},{id:'f3',name:'DockerConfigs',type:'folder',updatedAt:'2026-06-27',path:'DockerConfigs'},{id:'f4',name:'nas_manual.pdf',type:'file',size:'2.4 MB',updatedAt:'2026-05-12',extension:'pdf'}], Media:[{id:'m1',name:'Movies',type:'folder',updatedAt:'2026-06-24',path:'Media/Movies'},{id:'m2',name:'Music',type:'folder',updatedAt:'2026-06-23',path:'Media/Music'},{id:'m3',name:'family_photo.jpg',type:'file',size:'4.8 MB',updatedAt:'2026-06-15',extension:'jpg'}], 'Media/Movies':[{id:'mov1',name:'Big_Buck_Bunny.mp4',type:'file',size:'245 MB',updatedAt:'2026-06-10',extension:'mp4'},{id:'mov2',name:'Sintel_4K.mkv',type:'file',size:'1.2 GB',updatedAt:'2026-06-11',extension:'mkv'}], 'Media/Music':[{id:'mus1',name:'lofi_study_chill.mp3',type:'file',size:'8.2 MB',updatedAt:'2026-06-22',extension:'mp3'}], Backups:[{id:'b1',name:'MacBook_Backup.sparseimage',type:'file',size:'124 GB',updatedAt:'2026-06-20',extension:'sparseimage'},{id:'b2',name:'database_dump.sql',type:'file',size:'42 MB',updatedAt:'2026-06-26',extension:'sql'}], DockerConfigs:[{id:'d1',name:'docker-compose.yml',type:'file',size:'4.1 KB',updatedAt:'2026-06-27',extension:'yml'},{id:'d2',name:'plex_config',type:'folder',updatedAt:'2026-06-27',path:'DockerConfigs/plex_config'}] },
  services: [],
  tasks: []
};
const $ = (id) => document.getElementById(id);
const esc = (v='') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const formatBytes = (b) => b === 0 ? '0 B' : `${(b / 1024 ** Math.min(Math.floor(Math.log(b)/Math.log(1024)),4)).toFixed(1)} ${['B','KB','MB','GB','TB'][Math.min(Math.floor(Math.log(b)/Math.log(1024)),4)]}`;
const normalizePath = (p) => !p || p === 'root' ? 'root' : p.replace(/^\/+/, '');
const uptime = () => `${Math.floor(state.uptimeSeconds/86400)}d ${Math.floor(state.uptimeSeconds%86400/3600)}h ${Math.floor(state.uptimeSeconds%3600/60)}m`;
function toast(text){ $('toast').textContent = text; $('toast').classList.remove('hidden'); navigator.vibrate?.(50); setTimeout(()=>$('toast').classList.add('hidden'), 3600); }
async function parseJson(res){ const body = (res.headers.get('content-type')||'').includes('json') ? await res.json() : await res.text(); if(!res.ok) throw new Error(body.error || body.message || body || `Request failed ${res.status}`); return body; }
async function getOverview(){ return parseJson(await fetch(`${API}/overview`, {credentials:'same-origin'})); }
async function getFiles(path){ return parseJson(await fetch(path && path !== 'root' ? `${API}/files?path=${encodeURIComponent(path)}` : `${API}/files`, {credentials:'same-origin'})); }
function mapApiFiles(entries){ return entries.map(e => ({id:e.path,name:e.name,path:e.path,type:e.is_dir?'folder':'file',size:e.is_dir?undefined:formatBytes(e.size),updatedAt:e.mtime?new Date(e.mtime*1000).toISOString().split('T')[0]:'unknown',extension:e.name.includes('.')?e.name.split('.').pop():undefined})); }
async function refreshFiles(path='root'){ const data = await getFiles(path === 'root' ? null : path); state.files[data.current] = mapApiFiles(data.entries); if(data.current === data.root) state.files.root = state.files[data.current]; return data.current; }
function iconForFile(f){ if(f.type === 'folder') return '📁'; const e=(f.extension||'').toLowerCase(); if(['mp4','mkv','mov'].includes(e)) return '🎬'; if(['mp3','wav','flac'].includes(e)) return '🎵'; if(['jpg','png','svg','gif'].includes(e)) return '🖼'; if(['pdf','docx','txt','json'].includes(e)) return '📄'; return '▫'; }
function renderDashboard(){ const s=state.stats, used=s.disks.reduce((a,d)=>a+d.used,0), total=s.disks.reduce((a,d)=>a+d.total,0), pct=total?Math.round(used/total*100):0; $('server-title').textContent=s.serverName||'NAS-Server-01'; $('server-subtitle').textContent=`${s.platform||'NAS'} • Uptime: ${uptime()}`; $('dashboard-panel').innerHTML=`<div class="space"><div class="grid">${metric('CPU Load',Math.round(s.cpu)+'%','⚙',s.cpu)}${metric('RAM Usage',Math.round(s.ram)+'%','▰',s.ram)}${metric('System Temp',s.temp+'°C','🌡',Math.min(s.temp/85*100,100))}<div class="card metric"><span class="label">Network Rates</span><div><p class="row"><span>↓ DL</span><b>${speed(s.networkDown)}</b></p><p class="row"><span>↑ UL</span><b>${speed(s.networkUp)}</b></p></div></div></div><div class="card storage"><div class="section-head"><h3>💾 Storage Pools</h3><span class="muted">RAID-5 Array</span></div><p class="value">${pct}% <span class="label">used</span></p><p class="muted">${used.toLocaleString()} GB / ${total.toLocaleString()} GB</p><div class="bar"><div class="fill" style="width:${pct}%;background:${pct>85?'var(--rose)':pct>70?'var(--amber)':'var(--blue)'}"></div></div>${s.disks.map(d=>`<div class="drive row"><span>${d.status==='healthy'?'✅':'⚠️'} ${esc(d.name)}</span><span>${d.total?Math.round(d.used/d.total*100):0}% full · ${d.temp}°C</span></div>`).join('')}</div></div>`; }
function metric(label,value,icon,width){ return `<div class="card metric"><div class="metric-head"><span class="label">${label}</span><span>${icon}</span></div><div><span class="value">${value}</span><div class="bar"><div class="fill" style="width:${width}%"></div></div></div></div>`; }
function speed(k){ return k>1024 ? `${(k/1024).toFixed(1)} MB/s` : `${k.toFixed(0)} KB/s`; }
function renderFiles(){ const files=(state.files[state.currentPath]||[]).filter(f=>f.name.toLowerCase().includes(state.fileSearch.toLowerCase())); const crumbs=state.currentPath==='root'?['root']:['root',...state.currentPath.split('/')]; $('files-panel').innerHTML=`<div class="toolbar"><h2>File Station</h2><div class="toolbar-actions"><button id="new-folder">＋</button><button id="upload-open">⬆</button></div></div><input class="search" id="file-search" placeholder="Search files and folders..." value="${esc(state.fileSearch)}"><div class="breadcrumbs">${state.currentPath!=='root'?'<button class="chip" id="up-folder">←</button>':''}${crumbs.map((c,i)=>`<button class="chip ${i===crumbs.length-1?'active':''}" data-path="${i===0?'root':crumbs.slice(1,i+1).join('/')}">${esc(c==='root'?'NAS Storage':c)}</button>`).join('')}</div><div class="list-card">${files.length?files.map(f=>`<div class="file-row"><div class="file-main ${f.type==='folder'?'folder-link':''}" data-path="${esc(f.path||'')}"><span>${iconForFile(f)}</span><div><p class="file-name">${esc(f.name)}</p><p class="file-meta">${f.type==='folder'?'Folder':esc(f.size)} • ${esc(f.updatedAt)}</p></div></div><div>${f.type==='file'?`<button class="action download" data-path="${esc(f.path||'')}">↓</button>`:''}<button class="action delete" data-id="${esc(f.id)}">🗑</button></div></div>`).join(''):'<div class="empty">📁<br>No items found</div>'}</div>`; bindFiles(); }
function renderServices(){ $('apps-panel').innerHTML=`<div class="toolbar"><h2>App Center</h2><span class="badge">No apps installed</span></div><div class="empty">▦<br>Apps is empty for now.<br><span class="muted">Installable NAS applications can be added later per user.</span></div>`; }
function renderTasks(){ $('tasks-panel').innerHTML=`<div class="toolbar"><h2>Tasks</h2><button class="primary" id="open-add">＋ Record Task</button></div><form class="add-form hidden" id="add-form"><b>Record a Task</b><input id="download-link" required placeholder="Task name, URL, or note to save..."><div class="form-actions"><button type="button" id="cancel-add">Cancel</button><button class="primary" type="submit">Save Task</button></div></form>${state.tasks.length ? state.tasks.map(t=>`<div class="card task"><div class="task-head"><div class="file-main"><span class="task-icon">${taskIcon(t.type)}</span><div><p class="task-title">${esc(t.name)}</p><p class="meta-line muted"><span>${t.type.toUpperCase()}</span>${t.speed?`<span>↓ ${esc(t.speed)}</span>`:''}${t.eta?`<span>⏱ ${esc(t.eta)}</span>`:''}</p></div></div>${t.type==='download'?`<div>${t.status==='active'?`<button class="task-control pause" data-id="${t.id}">⏸</button>`:t.status==='paused'?`<button class="task-control resume" data-id="${t.id}">▶</button>`:''}<button class="task-control cancel" data-id="${t.id}">×</button></div>`:''}</div><div><div class="row"><span class="badge ${t.status}">${t.status}</span><b>${Math.round(t.progress)}%</b></div><div class="bar"><div class="fill" style="width:${t.progress}%;background:${t.status==='completed'?'var(--green)':t.status==='paused'?'#475569':'linear-gradient(90deg,var(--blue),var(--indigo))'}"></div></div></div></div>`).join('') : '<div class="empty">✓<br>No saved tasks yet</div>'}`; bindTasks(); }
const taskIcon = (t) => ({download:'↓',backup:'✅',raid:'⚠️',sync:'↻'}[t]||'↓');

async function getAuth(){ return parseJson(await fetch(`${API}/auth/status`, {credentials:'same-origin'})); }
async function login(username,password,register=false){ return parseJson(await fetch(`${API}/auth/${register?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({username,password})})); }
async function getTasks(){ return parseJson(await fetch(`${API}/tasks`, {credentials:'same-origin'})); }
async function saveTask(task){ return parseJson(await fetch(`${API}/tasks`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(task)})); }
async function patchTask(id, patch){ return parseJson(await fetch(`${API}/tasks/${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(patch)})); }
async function deleteTask(id){ return parseJson(await fetch(`${API}/tasks/${encodeURIComponent(id)}`,{method:'DELETE',credentials:'same-origin'})); }
function renderAuth(){ let panel=$('auth-panel'); if(state.auth.authenticated){ panel?.remove(); return; } if(!panel){ panel=document.createElement('div'); panel.id='auth-panel'; panel.className='modal'; document.body.appendChild(panel); } const mode=state.auth.registration_open?'Create NAS account':'Sign in'; panel.innerHTML=`<div class="modal-card"><h3>${mode}</h3><p class="muted">Per-user NAS access keeps files and saved tasks private.</p><form id="auth-form"><input id="auth-user" required minlength="3" autocomplete="username" placeholder="Username"><input id="auth-pass" required minlength="8" type="password" autocomplete="current-password" placeholder="Password"><button class="primary" type="submit">${mode}</button></form></div>`; $('auth-form').onsubmit=async e=>{e.preventDefault(); try{ await login($('auth-user').value.trim(), $('auth-pass').value, state.auth.registration_open); state.auth=await getAuth(); await refreshFiles(); const data=await getTasks(); state.tasks=data.tasks||[]; renderAuth(); render(); toast('NAS session ready'); }catch(err){ toast(err.message||'Authentication failed'); } }; }
async function refreshOverview(){ const o=await getOverview(); state.stats={serverName:o.server_name,platform:o.platform,nasRoot:o.nas_root,cpu:o.cpu_percent,ram:o.ram_percent,temp:o.temp_c||0,networkUp:o.net_ul_kbs,networkDown:o.net_dl_kbs,disks:(o.drives.length?o.drives:[{device:o.nas_root,mountpoint:o.nas_root,percent:o.disk_percent,used_gb:o.disk_used_gb,total_gb:o.disk_total_gb}]).map(d=>({name:d.device||d.mountpoint,used:d.used_gb,total:d.total_gb,temp:o.temp_c||0,status:d.percent>90?'critical':d.percent>75?'warning':'healthy'}))}; renderDashboard(); }
function render(){ renderAuth(); renderDashboard(); renderFiles(); renderServices(); renderTasks(); document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('hidden', !p.id.startsWith(state.activeTab))); document.querySelectorAll('.bottom-tabs button').forEach(b=>b.classList.toggle('active', b.dataset.tab===state.activeTab)); }
function bindFiles(){ $('file-search').oninput=e=>{state.fileSearch=e.target.value; renderFiles();}; $('new-folder').onclick=()=> $('folder-modal').classList.remove('hidden'); $('upload-open').onclick=()=> $('upload-modal').classList.remove('hidden'); $('up-folder')?.addEventListener('click',()=>{const p=state.currentPath.split('/'); p.pop(); state.currentPath=p.join('/')||'root'; renderFiles();}); document.querySelectorAll('[data-path]').forEach(b=>b.onclick=async()=>{const p=normalizePath(b.dataset.path); if(!p)return; try{state.currentPath=await refreshFiles(p); state.fileSearch='';}catch{state.currentPath=p;} renderFiles();}); document.querySelectorAll('.folder-link').forEach(el=>el.onclick=async()=>{try{state.currentPath=await refreshFiles(el.dataset.path);}catch{state.currentPath=normalizePath(el.dataset.path);} renderFiles();}); document.querySelectorAll('.download').forEach(b=>b.onclick=()=>{ if(b.dataset.path){ location.href=`${API}/download?path=${encodeURIComponent(b.dataset.path)}`; toast('Downloading file'); }}); document.querySelectorAll('.delete').forEach(b=>b.onclick=async()=>{ const item=(state.files[state.currentPath]||[]).find(f=>f.id===b.dataset.id); if(!item?.path)return; try{ await parseJson(await fetch(`${API}/delete?path=${encodeURIComponent(item.path)}`,{method:'DELETE',credentials:'same-origin'})); await refreshFiles(state.currentPath); toast('Removed item'); }catch(err){ toast(err.message||'Delete failed'); } renderFiles(); }); }
function bindServices(){ document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.serviceFilter=b.dataset.filter; renderServices();}); $('service-search').oninput=e=>{state.serviceSearch=e.target.value; renderServices();}; document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>toggleService(b.dataset.service)); document.querySelectorAll('[data-webui]').forEach(a=>a.onclick=e=>{e.preventDefault(); a.textContent='Connecting...'; setTimeout(()=>a.textContent='Web UI ↗',1500);}); }
function bindTasks(){ $('open-add').onclick=()=>$('add-form').classList.remove('hidden'); $('cancel-add').onclick=()=>$('add-form').classList.add('hidden'); $('add-form').onsubmit=e=>{e.preventDefault(); addTask($('download-link').value.trim());}; document.querySelectorAll('.pause').forEach(b=>b.onclick=async()=>{const t=state.tasks.find(t=>t.id===b.dataset.id); Object.assign(t,{status:'paused',speed:undefined,eta:undefined}); await patchTask(t.id,{status:t.status,speed:t.speed,eta:t.eta}); toast('Task paused'); renderTasks();}); document.querySelectorAll('.resume').forEach(b=>b.onclick=async()=>{const t=state.tasks.find(t=>t.id===b.dataset.id); Object.assign(t,{status:'active',speed:'18.0 MB/s',eta:'30s'}); await patchTask(t.id,{status:t.status,speed:t.speed,eta:t.eta}); toast('Task resumed'); renderTasks();}); document.querySelectorAll('.cancel').forEach(b=>b.onclick=async()=>{await deleteTask(b.dataset.id); state.tasks=state.tasks.filter(t=>t.id!==b.dataset.id); toast('Task deleted'); renderTasks();}); }
function toggleService(id){ const s=state.services.find(x=>x.id===id); if(s.status==='running'){Object.assign(s,{status:'stopped',uptime:undefined,cpuUsage:0,ramUsage:0}); toast(`${s.name} stopped`); renderServices();} else {s.status='starting'; toast(`Starting ${s.name}...`); renderServices(); setTimeout(()=>{Object.assign(s,{status:'running',uptime:'0s',cpuUsage:+(2.5+Math.random()*4).toFixed(1),ramUsage:Math.round(50+Math.random()*120)}); toast(`${s.name} is now running`); renderServices();},1800);} }
async function addTask(link){ if(!link)return; const filename=(link.includes('/') ? (link.split('/').pop()||link) : link).slice(0,160); const task={id:`task-${Date.now()}`,name:filename,type:'download',progress:0,speed:'25.6 MB/s',eta:'35s',status:'active'}; try{ const saved=await saveTask(task); state.tasks.unshift(saved.task||task); $('download-link').value=''; $('add-form').classList.add('hidden'); toast(`Saved task: ${filename}`); renderTasks(); }catch(err){ toast(err.message||'Task save failed'); } }
function tickTime(){ const d=new Date(); $('current-time').textContent=d.toLocaleTimeString([], {hour:'numeric', minute:'2-digit'}); }
function simulate(){ state.uptimeSeconds++; let changed=false; state.tasks.forEach(t=>{ if(t.status!=='active')return; const rate=t.type==='download'?2.4:t.type==='raid'?.08:.5; t.progress=Math.min(100,t.progress+rate); changed=true; if(t.progress>=100){t.status='completed'; t.speed=undefined; t.eta=undefined; toast(`${t.name} has completed!`);} }); if(changed && state.activeTab==='tasks') renderTasks(); }
async function init(){ state.auth=await getAuth().catch(()=>state.auth); renderAuth(); document.querySelectorAll('.bottom-tabs button').forEach(b=>b.onclick=()=>{state.activeTab=b.dataset.tab; render();}); $('control-toggle').onclick=()=>$('control-center').classList.toggle('hidden'); document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast)); document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden')); $('folder-form').onsubmit=async e=>{e.preventDefault(); const name=$('folder-name').value.trim(); if(!name)return; try{ await parseJson(await fetch(`${API}/folder`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({name,path:state.currentPath==='root'?'':state.currentPath})})); await refreshFiles(state.currentPath); toast(`Folder created: ${name}`); renderFiles(); }catch(err){ toast(err.message||'Folder creation failed'); } $('folder-name').value=''; $('folder-modal').classList.add('hidden');}; $('upload-form').onsubmit=async e=>{e.preventDefault(); const file=$('upload-file').files[0]; if(!file)return; try{const form=new FormData(); form.append('file',file); await parseJson(await fetch(`${API}/upload?path=${encodeURIComponent(state.currentPath==='root'?'':state.currentPath)}`,{method:'POST',credentials:'same-origin',body:form})); await refreshFiles(state.currentPath); toast('Upload complete'); renderFiles();}catch(err){toast(err.message||'Upload failed');} $('upload-modal').classList.add('hidden');}; tickTime(); render(); refreshOverview().catch(()=>{}); refreshFiles().then(()=>renderFiles()).catch(()=>{}); getTasks().then(d=>{state.tasks=d.tasks||[]; renderTasks();}).catch(()=>{}); setInterval(tickTime,15000); setInterval(refreshOverview,10000); setInterval(simulate,2000); }
document.addEventListener('DOMContentLoaded', init);
